### ISSUE TITLE
Bad ram usage with scenebuilder

### ISSUE THREAD

**Issue by SaeedMasoumi** [jfoenixadmin/JFoenix#52]
Hi,
I created a simple `Pane` with a `JFXProgressBar` as child in it. When i added `JFXProgressBar`, my ram usage suddenly started to increase rapidly.

![jfoenix-ram-usage](https://cloud.githubusercontent.com/assets/6934577/13563541/bdcf3f10-e457-11e5-9f3d-8b27d4ad5868.png) 

So in 1 minute it takes approximately 5 GB ram :), As soon as i remove `JFXProgressBar` my ram usage stopped and in the next GC call it dropped to 4 GB.

**Comment by SaeedMasoumi** [comment]
I forgot to mention my SceneBuilder version, I'm using Gluon SceneBuilder v8.1.1

**Comment by RAnders00** [comment]
I tried what you described and was not able to reproduce it:

![image](https://cloud.githubusercontent.com/assets/1629196/13576216/df028f7c-e48c-11e5-8a23-28d3802a268b.png)

You can see that the heap size does not grow over time for me. Also, it does not even come close to the amount of growth you are describing (5 GB in 1 minute).

The green horizontal line is to demonstrate that the heap does not accumulate ("leaks") memory over time.

That's why I kindly ask you to reproduce the issue on your end.

## Getting the latest JFoenix build

Maybe the version of JFoenix you still have is outdated or the one offered for download still contains the issue.

* Do you have the bleeding edge version of JFoenix? Clone the repo, run `./gradlew jfoenix:jar` and pick the `jfoenix-0.0.0-SNAPSHOT.jar` from `subprojects/jfoenix/build/libs/` to import it to SceneBuilder.
    * To replace already imported jars in SceneBuilder, reveal imported jars in the file explorer:
    ![image](https://cloud.githubusercontent.com/assets/1629196/13576088/284a4f22-e48c-11e5-8e57-7e6cd2e5622d.png)
    * Close SceneBuilder
    * Delete the existing JFoenix jar
    * Move the new freshly built jar there

After that, see if you can still reproduce the memory growth.

## Collecting heap snapshots

If you are still experiencing the growth, do this:

* Open SceneBuilder, but do not add the `JFXProgressBar` to the document yet.
* Open JVisualVM (it's a binary located where `java`, `javac`, `javaw`, etc... are)
* On the left hand side, select the JVM SceneBuilder is running on. It will probably not be possible to tell right away, so just open them one by one and see if the opened tab on the right mentions something related to SceneBuilder.
* Now that you are connected to the SceneBuilder JVM, add the `JFXProgressBar` to the document. Now, wait a moment until you feel like enough memory has been allocated.
* Take a heap dump. The button for doing so is located on the _Monitor_ tab.
![image](https://cloud.githubusercontent.com/assets/1629196/13576539/86b7f77e-e48e-11e5-8d0c-34c1bca68d99.png)
* A new tab full of information will open. Ignore it for now.
* Close SceneBuilder for now.
* On the left hand side, right-click the just collected heap dump and select _Save As..._.
![image](https://cloud.githubusercontent.com/assets/1629196/13576560/a3ea9fea-e48e-11e5-82ea-c76bb969d4fe.png)
* Save the resulting file somewhere.
* Upload the file somewhere. Some tips:
    * The heap dump is uncompressed. I highly recommend zipping it. (for me, I was able to reduce a 50 MB heap dump down to 9 MB)
    * GitHub itself is capable of attaching files up to 10 MB. See the grey bar below the post editor.
    * Just a tip regarding file hosters: [pantsu.cat](https://pantsu.cat/) if the zipped file is below 128 MB and something like [ge.tt](http://ge.tt/) (you need to register) for things below 2 GB.
* Post the download link in this thread, I will then be able to see what causes the high memory usage (hopefully).

**Comment by SaeedMasoumi** [comment]
First of all thank you for your guideline :)

I tried to test that in my mac book but i can't reproduce it and there is no extra memory usage **But** on my PC which runs on Fedora23 i can reproduce it every time. (actually 16 GB ram getting full after 5 or 6 minutes )
In both, i use same SceneBuilder version & latest version of JFoenix .

So here is memory usage of SceneBuilder in my fedora after 1 minute
![screenshot from 2016-03-07 21-24-12](https://cloud.githubusercontent.com/assets/6934577/13578351/b52e97ca-e4ac-11e5-9fe9-7de5c70130a8.png)
And my heap dump too
![screenshot from 2016-03-07 21-40-45](https://cloud.githubusercontent.com/assets/6934577/13578451/4cb6d0c6-e4ad-11e5-863c-ff4ba4a40c89.png)

[heapdump-1457373573126.hprof.zip](https://github.com/jfoenixadmin/JFoenix/files/161835/heapdump-1457373573126.hprof.zip)

**Comment by RAnders00** [comment]
Oh wow, I did not expect that. It looks like something is allocating insane amounts of memory **outside** of the Heap (in native memory) which suggests there is a bug in JavaFX. The memory usage in the graph you have shown is perfectly normal (like expected) but something is rapidly growing outside of the heap (which is where all object allocated inside of java live), which suggests that native JavaFX code is leaking it. The amount of objects allocated inside of Java's heap is 25 MB only.

Now I'm out of direct knowledge and I can only offer things that may or may not help. I'm just guessing what could be the problem.

* Have you validated that you have the latest version of Java (preferably the one shipped by Oracle)
* Try to launch SceneBuilder with software rendering only:

    ```sh
    java -Dprism.order=sw -Dprism.verbose=true -jar "SceneBuilder-8.1.1.jar" 2>&1 | tee scenebuilder.log
    ```

Get the executable jar (if you are not already using it) from [here](http://gluonhq.com/open-source/scene-builder/).

You might need to re-import the JFoenix jar.

There is no need to make any more heap dumps, since they do not capture the problem. Just report back whether the issue still occurs and attach the `scenebuilder.log` (maybe verbose prism output yields something useful).

**Comment by SaeedMasoumi** [comment]
Oh great my problem was solved with your second way, Thank you.
But can you explain what  `-Dprism.order=sw -Dprism.verbose=true` means ?

**Comment by SaeedMasoumi** [comment]
Here is log message
```
Prism pipeline init order: sw 
Using java-based Pisces rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
(X) Got class = class com.sun.prism.sw.SWPipeline
Initialized prism pipeline: com.sun.prism.sw.SWPipeline
 vsync: true vpipe: false
Mar 07, 2016 10:04:05 PM com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher exploreAndUpdateLibrary
INFO: Start exploring JAR /home/saeed/.scenebuilder/Library/jfoenix.jar
Mar 07, 2016 10:04:06 PM com.oracle.javafx.scenebuilder.app.SceneBuilderApp logTimestamp
INFO: JavaFX Scene Builder started
```
And ram usage 
![screenshot from 2016-03-07 22-05-39](https://cloud.githubusercontent.com/assets/6934577/13579362/73c3da56-e4b2-11e5-93b8-cac05ba605b4.png)

**Comment by RAnders00** [comment]
Basically, `-Dprism.order=sw` disables hardware acceleration (which runs in native code, that's why I suspected) and renders everything using Java code instead.

`-Dprism.verbose=true` enables verbose logging output by the JavaFX renderer. You can leave that out in the future, I figured it might help in case your problem was not solved by enforcing software rendering.

You should probably file Java bug report regarding this issue or search for JavaFX issues regarding Fedora on the internet. This issue is not directly caused by a fault in JFoenix and has to be fixed from the JavaFX side.

**Comment by SaeedMasoumi** [comment]
Thank you, 
Another weird thing, i have two graphic cards on my fedora (nvidia & intel). By default whole system runs on Intel, so i decided to switch to nVidia and run SceneBuilder with that. Then i saw there is no memory issue anymore

**Comment by juzimmer** [comment]
I'm having massive memory usages with this as well. Where am I suppose to enter that code ? is that in the properties of the scenebuilder exe ?
